<?php
/* !! PLEASE DO NOT EDIT THIS FILE !! */

	/*
	 * @Project:
	 * ServInfo Server Information Manager
	 * Owner: DigTek (Elite Star Services)
	 * Web: https://servinfo.elite-star-services.com/
	 * 
	 * License: GPL v3 | https://elite-star-services.com/license/
	*/
	
?>
<div class="container-fluid">
<hr>
	<div class="text-center center-block">
	<p class="txt-railway"><a href="https://servinfo.elite-star-services.com/"><?php echo "ServInfo Server v".$serverVersion; ?></a></p>
	</div>
</div>