<?php
// THIS FILE IS NOT AFFECTED BY UPGRADES AND IS SAFE TO EDIT

// COMMENT OUT THE LINE BELOW TO DISABLE REDIRECT AND PUT FOLDER BROWSING BLOCK IN PLACE / UNCOMMENT WILL REDIRECT TO SERVINFO SITE
//echo '<META HTTP-EQUIV="Refresh" Content="0; URL=https://servinfo.elite-star-services.com/">';
// UNCOMMENT THE LINE BELOW AND COMMENT OUT THE LINE ABOVE TO REDIRECT TO THE SHOW SERVERS PAGE (SERVER ONLY)
echo '<META HTTP-EQUIV="Refresh" Content="0; URL=sho_srv.php">';
?>