<?php
/* !! DO NOT EDIT THIS FILE !! */

	/*
	 * @Project:
	 * ServInfo Server Information Manager
	 * Author: DigTek (Elite Star Services)
	 * Web: https://elite-star-services.com/servinfo
	 * 
	 * License: GPL v3 | https://elite-star-services.com/license/
	*/


require('head.php');



// NEEDED FOR TOKEN AND DATABASE PAGES - REQUIRED IN HEAD NOW
//require('ss_cnf.php');



?>
<title>ServInfo - Add / Update Server</title>
<?php


// IF NO FORM DATA
if(!isset($_GET['server'])) {

?>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
				<?php echo "<b>Add New Server</b>&nbsp;&nbsp;<small>* A properly configured ServInfo Client must already be installed on the server. *</small>"; ?>
				</div>
			<div class="panel-body">
<?php
echo '<form method="get" action="'.$_SERVER['PHP_SELF'].'">';
echo '<b>Enter Client Token</b>';
echo '<div class="pull-right"><input type="text" name="token" size="62"></div>';
echo '<hr align="left" width="50%"><b>Enter Script URL</b> (shown in Client)';
echo '<div class="pull-right"><input type="text" name="server" size="62"></div><br><br>';
echo '<input type="submit" value="Add Server" name="submit">';
echo '</form>';
?>
			</div>
			</div>
		</div>
	</div>
</div>



<?php
// IF FORM DATA
} else {



// BEGIN POLL SERVER LOGIC



// CHECK IF ADDING OR UPDATING SERVER
if ((isset($_GET['update'])) OR (isset($_GET['delete']))) {

	$serverID = mysqli_real_escape_string($db, $_GET['server']);
	$getURL = "SELECT pass_db, url_db FROM servdata WHERE sid_db LIKE '$serverID'";
	if (!$result_url = $db->query($getURL)) { die('There was an error running the query [' . $db->error . ']'); }
	$row_u = mysqli_fetch_array($result_url);
	$scriptURL = $row_u["url_db"];
	$token = $row_u["pass_db"];

} else {  
	$scriptURL = mysqli_real_escape_string($db, $_GET['server']);
	$token = mysqli_real_escape_string($db, $_GET['token']);
}





// patch if client < v0.9.4
$chkU = substr($scriptURL, -1);
if ($chkU != '/') {

$baseURL = $scriptURL;
$post_url = '/servinfo/servinfo.php?'.$token;

} else {
// GET BASE URL FROM SCRIPT URL
$tmp_url = explode('://', $scriptURL);
$exPath = strchr($tmp_url[1], '/');
$baseURL = str_replace($exPath, '', $scriptURL);
$post_url = 'servinfo.php?'.$token;
//echo $baseURL;
}



// CONVERT URL TO DOMAIN
$url2dom = explode("://", $baseURL);
$domain = $url2dom[1];




// DO NOT POLL IF DELETING
if(!isset($_GET['delete'])) {

// BUILD JSON REQUEST
$main_url = $scriptURL;

$method = "GET";

$full_url = $main_url.$post_url.'&json';

// CREATE THE JSON ARRAY
$my_data = array(
  'http'=>array(
    'method'=>"$method",
    'header'=>
              "Content-type: application/json\r\n"
  )
);

$request = stream_context_create($my_data);

// SEND THE REQUEST TO SERVER
$page = file_get_contents($full_url, false, $request);
$data = json_decode($page, TRUE);

//print_r($page);
//print_r($data);

// DIE HERE IF NO DATA IN REQUEST
if ($data == NULL) { die("ERROR - No Client Found @ ".$full_url.": Check Server and ServInfo Requirements..."); } else {




?>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
<div class="panel-heading">
	<?php echo "<b>Client Found @ ".$main_url."</b>"; ?>
</div>
	<div class="panel-body">
<?php

// BUILD SERVER DATA
	foreach ($data as $key => $value) {
	echo $key.' = '.$value.'<br>';

if ($key == "SID") { $sid = mysqli_real_escape_string($db, $value); }
if ($key == "URL") { $url = mysqli_real_escape_string($db, $value); }
if ($key == "IP") { $ip = mysqli_real_escape_string($db, $value); }
if ($key == "PASS") { $token = mysqli_real_escape_string($db, $value); }
if ($key == "HOST") { $host = mysqli_real_escape_string($db, $value); }
if ($key == "RUN") { $run = mysqli_real_escape_string($db, $value); }
if ($key == "OS") { $os = mysqli_real_escape_string($db, $value); }
if ($key == "KER") { $ker = mysqli_real_escape_string($db, $value); }
if ($key == "GUI") { $gui = mysqli_real_escape_string($db, $value); }
if ($key == "VM") { $vm = mysqli_real_escape_string($db, $value); }
if ($key == "CPU") { $cpu = mysqli_real_escape_string($db, $value); }
if ($key == "MEM") { $mem = mysqli_real_escape_string($db, $value); }
if ($key == "WEB") { $web = mysqli_real_escape_string($db, $value); }
if ($key == "WWW") { $www = mysqli_real_escape_string($db, $value); }
if ($key == "USER") { $user = mysqli_real_escape_string($db, $value); }
if ($key == "PHP") { $php = mysqli_real_escape_string($db, $value); }
if ($key == "SSL") { $ssl = mysqli_real_escape_string($db, $value); }
if ($key == "SQL") { $sql = mysqli_real_escape_string($db, $value); }
if ($key == "GIT") { $git = mysqli_real_escape_string($db, $value); }
if ($key == "VER") { $scv = mysqli_real_escape_string($db, $value); }
if ($key == "WPV") { $wpv = mysqli_real_escape_string($db, $value); }

	}

	$ver = $scv.','.$wpv;
	$date = date('n/j/Y');
	echo 'Todays Date = '.$date.'<hr>';
	
}

}


// CHECK IF SERVER IN DATABASE
$getServ = "SELECT sid_db FROM servdata WHERE sid_db LIKE '$serverID'";
if (!$result_serv = $db->query($getServ)) { die('There was an error running the query [' . $db->error . ']'); }
$row_serv = $result_serv->num_rows;

//$row_s = mysqli_fetch_array($result_serv);
//$serv_ip = $row_s["ip"];

//echo $serv_ip.'<br>';
//echo $row_serv.'<br>';

if ($row_serv == 0) {


	// INSERT SERVER
echo "New Server ".$domain." Added to ServInfo Database...<br><small><a href='".$scriptURL.$post_url."'>VIEW DETAILED INFO FOR THIS SERVER</a>";
	$sqi = "INSERT INTO servdata (sid_db, url_db, ip_db, pass_db, host_db, run_db, os_db, ker_db, gui_db, vm_db, cpu_db, mem_db, web_db, www_db, user_db, php_db, ssl_db, sql_db, git_db, ver_db, last_update)
	VALUES ('$sid', '$url', '$ip', '$token', '$host', '$run', '$os', '$ker', '$gui', '$vm', '$cpu', '$mem', '$web', '$www', '$user', '$php', '$ssl', '$sql', '$git', '$ver', '$date')";
	if (!$result = $db->query($sqi)) { die('There was an error running insert the query [' . $db->error . ']'); }

	
} else { 


	// DELETE SERVER
	if(isset($_GET['delete'])) { 
?>
<div class="container">
 <div class="row">
  <div class="col-md-12">
   <div class="panel panel-default">
	<div class="panel-heading bold-text">
		Delete Server from ServInfo
	</div>
<div class="panel-body">
<?php

$sqd = "DELETE FROM servdata WHERE sid_db = '$serverID'";
if (!$result = $db->query($sqd)) { die('There was an error running the delete query [' . $db->error . ']'); }

echo "Server ".$domain." deleted from ServInfo Database...<br><small><i>Client software was NOT removed</i></small>";


	} else {
	

	// UPDATE SERVER
echo "Server ".$domain." Updated...<br><small><a href='".$scriptURL.$post_url."'>VIEW DETAILED INFO FOR THIS SERVER</a>";
$squ = "UPDATE servdata SET url_db = '$url', ip_db = '$ip', pass_db = '$token', host_db = '$host', run_db = '$run', os_db = '$os', ker_db = '$ker', gui_db = '$gui', vm_db = '$vm', cpu_db = '$cpu', mem_db = '$mem', web_db = '$web', www_db = '$www', user_db = '$user', php_db = '$php', ssl_db = '$ssl', sql_db = '$sql', git_db = '$git', ver_db = '$ver', last_update = '$date' WHERE sid_db = '$serverID'";
if (!$result = $db->query($squ)) { die('There was an error running the update query [' . $db->error . ']'); }
	}

}

?>
			</div>
			</div>
		</div>
	</div>
</div>
<?php

}


include('foot.php');
?>