<?php
/* !! DO NOT EDIT THIS FILE !! */

	/*
	 * @Project:
	 * ServInfo Server Information Manager
	 * Author: DigTek (Elite Star Services)
	 * Web: https://elite-star-services.com/servinfo
	 * 
	 * @License:
	 * GPL v3 | https://elite-star-services.com/license/
	*/

require('head.php');



// NEEDED FOR TOKEN AND DATABASE PAGES - REQUIRED IN HEAD NOW
//require('ss_cnf.php');



// GET SERVER DATA
$sqh = "select * from servdata";
if (!$result = $db->query($sqh)) { die('There was an error running the get query [' . $db->error . ']'); }


?>
<title>ServInfo - Update All Servers</title>
<!-- UNCOMMENT FOR FULL WIDTH PAGE
</div><div class="panel-body">
-->
<div class="container">
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading"><center><b>UPDATE ALL SERVERS</b></center></div>
			<div class="panel-body">
<?php


		while ($row = $result->fetch_assoc()) {


// BEGIN POLL SERVER LOGIC
$serverID = $row["sid_db"];
$scriptURL = $row["url_db"];
$token = $row["pass_db"];



// patch if client < v0.9.4
$chkU = substr($scriptURL, -1);
if ($chkU != '/') {

$baseURL = $scriptURL;
$post_url = '/servinfo/servinfo.php?'.$token;

} else {
// GET BASE URL FROM SCRIPT URL
$tmp_url = explode('://', $scriptURL);
$exPath = strchr($tmp_url[1], '/');
$baseURL = str_replace($exPath, '', $scriptURL);
$post_url = 'servinfo.php?'.$token;
//echo $baseURL;
}



// CONVERT URL TO DOMAIN
$url2dom = explode("://", $baseURL);
$domain = $url2dom[1];



//CHECK STATUS USING PING
$online = "ONLINE";
$ploop = 1;
unset($output);
exec("ping -c 1 -w 1 $domain", $output);
foreach($output as $response){
	if ($ploop == 4) { 
	$ping = $response;
	}
	$ploop++;
//  echo $response."<br>";
  if (strpos($response, "100%") !== false) { $online = "OFFLINE"; }
}


	if ($online == "OFFLINE") { echo "ERROR - ".$domain." is ".$online.": Skipping Update...<br>".substr($ping, 0, -10)."<hr>"; } else { 


$main_url = $scriptURL;

//$post_url = '/servinfo/servinfo.php?'.$token;

$method = "GET";

$full_url = $main_url.$post_url.'&json';

// CREATE THE HEADERS & CONTENT
$my_data = array(
  'http'=>array(
    'method'=>"$method",
    'header'=>
              "Content-type: application/json\r\n"
  )
);

$request = stream_context_create($my_data);


// SEND THE REQUEST TO SERVER
$page = file_get_contents($full_url, false, $request);
$data = json_decode($page, TRUE);
//$data = json_decode($page, false);

if ($data == NULL) { echo "ERROR - No Client Found @ ".$full_url.": Check Server and ServInfo requirements...<hr>"; } else {

//print_r($page);
//print_r($data);


echo "<b>Client Found @ ".$main_url."</b><br>";


	foreach ($data as $key => $value) {

$wpv = '';

	echo $key.' = '.$value.'<br>';

	if ($key == "SID") { $sid = mysqli_real_escape_string($db, $value); }
	if ($key == "URL") { $url = mysqli_real_escape_string($db, $value); }
	if ($key == "IP") { $ip = mysqli_real_escape_string($db, $value); }
	if ($key == "PASS") { $token = mysqli_real_escape_string($db, $value); }
	if ($key == "HOST") { $host = mysqli_real_escape_string($db, $value); }
	if ($key == "RUN") { $run = mysqli_real_escape_string($db, $value); }
	if ($key == "OS") { $os = mysqli_real_escape_string($db, $value); }
	if ($key == "KER") { $ker = mysqli_real_escape_string($db, $value); }
	if ($key == "GUI") { $gui = mysqli_real_escape_string($db, $value); }
	if ($key == "VM") { $vm = mysqli_real_escape_string($db, $value); }
	if ($key == "CPU") { $cpu = mysqli_real_escape_string($db, $value); }
	if ($key == "MEM") { $mem = mysqli_real_escape_string($db, $value); }
	if ($key == "WEB") { $web = mysqli_real_escape_string($db, $value); }
	if ($key == "WWW") { $www = mysqli_real_escape_string($db, $value); }
	if ($key == "USER") { $user = mysqli_real_escape_string($db, $value); }
	if ($key == "PHP") { $php = mysqli_real_escape_string($db, $value); }
	if ($key == "SSL") { $ssl = mysqli_real_escape_string($db, $value); }
	if ($key == "SQL") { $sql = mysqli_real_escape_string($db, $value); }
	if ($key == "GIT") { $git = mysqli_real_escape_string($db, $value); }
	if ($key == "VER") { $scv = mysqli_real_escape_string($db, $value); }
	if ($key == "WPV") { $wpv = mysqli_real_escape_string($db, $value); }

	}

	$ver = $scv.','.$wpv;
	$date = date('n/j/Y');
	echo 'Todays Date = '.$date.'<br>';

// SID DOES NOT UPDATE HERE - IT IS ALREADY THE SERVER ID
$squ = "UPDATE servdata SET url_db = '$url', ip_db = '$ip', pass_db = '$token', host_db = '$host', run_db = '$run', os_db = '$os', ker_db = '$ker', gui_db = '$gui', vm_db = '$vm', cpu_db = '$cpu', mem_db = '$mem', web_db = '$web', www_db = '$www', user_db = '$user', php_db = '$php', ssl_db = '$ssl', sql_db = '$sql', git_db = '$git', ver_db = '$ver', last_update = '$date' WHERE sid_db = '$serverID'";
if (!$result2 = $db->query($squ)) { die('There was an error running the update query [' . $db->error . ']'); }

	echo '<b>Server '.$domain.' Updated...</b><hr>';
	
}

	}

		}

echo '<small>SERVER UPDATE COMPLETE</small>';

?>
			</div>
		</div>
	</div>
</div>


<?php
include('foot.php');
?>